import { AppShell, Badge, BlockchainStatus, Card, MetricCard, PortfolioChart, SecurityStatus, TokenBalance, TokenCard, TokenHero, TransactionTable, WalletAddress, Web3Button } from '@rhc/ui';
import { navFor } from '../web3-nav';
import { DirectoryCards, IdentityCard, IdentityDetails, LinkedProperties, Notifications } from '../components/customer-data';

export default function Page() {
  return <AppShell title="RHC Web3 Dashboard" navItems={navFor('Dashboard')}>
    <section id="dashboard" className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <div className="rhc-card rhc-card-token border bg-[var(--rhc-surface)] p-6 shadow-sm md:p-7"><Badge tone="gold">RHC Web3 Ecosystem Overview</Badge><h2 className="rhc-page-title mt-5 max-w-3xl">Real assets. Digital ownership. Connected through Web3.</h2><p className="rhc-body-copy mt-4 max-w-3xl">Your digital identity, authorized property records, and notifications. Wallet, rewards, marketplace transactions, and blockchain features are coming soon.</p><div className="mt-7 flex flex-wrap gap-3"><Web3Button href="/token">View RHC Token</Web3Button><Web3Button href="#wallet" variant="secondary">Open Wallet Summary</Web3Button><Web3Button href="#digital-id" variant="secondary">Review Digital ID</Web3Button></div></div><IdentityCard />
    </section>
    <section className="mt-5"><TokenHero /></section>
    <section className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="RHC Token Supply" value="Not live" detail="Awaiting blockchain deployment" icon="RHC" /><MetricCard label="RHC Points" value="—" detail="Coming soon — Month 2" icon="PT" /><Card title="Digital Properties"><p className="text-sm text-[var(--rhc-muted)]">Authorized account relationships</p><div className="mt-4"><Web3Button href="/properties" variant="secondary">View linked properties</Web3Button></div></Card><MetricCard label="Wallet Status" value="Not connected" detail="No custody or real transfer active" icon="WL" /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><PortfolioChart /><div className="grid gap-6"><Card id="wallet" title="RHC Wallet"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--rhc-muted)]">Total Portfolio Value</p><p className="mt-2 text-2xl font-semibold text-[var(--rhc-heading)]">Coming soon</p></div><WalletAddress /></div><div className="mt-6 grid gap-3 sm:grid-cols-4">{['SEND', 'RECEIVE', 'TRANSFER', 'QR'].map((action) => <Web3Button key={action} variant="secondary">{action}</Web3Button>)}</div></Card><TokenCard /></div></section>
    <section id="digital-id" className="mt-5 grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><IdentityDetails /><IdentityCard /></section>
    <section id="points" className="mt-5 grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><Card title="RHC Points"><p className="text-sm leading-6 text-[var(--rhc-muted)]">Rewards are coming soon. RHC Points are separate from the future RHC Token; no live rewards balance is connected.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><TokenBalance /><TokenBalance label="Pending Rewards" /></div><div className="mt-6 flex flex-wrap gap-3"><Web3Button>Earn</Web3Button><Web3Button variant="secondary">Transfer</Web3Button><Web3Button variant="secondary">Redeem</Web3Button></div></Card><Card title="Token Information"><div className="grid gap-3 sm:grid-cols-2">{[['Reward Name', 'RHC Points'], ['Symbol', 'RHC Points'], ['Network', 'Not connected'], ['Contract Address', 'Not a token contract'], ['Total Supply', 'Not available'], ['Status', 'Coming soon — Month 2']].map(([label, value]) => <div key={label} className="rounded-lg border border-[var(--rhc-border)] bg-[var(--rhc-surface-secondary)] p-4"><p className="text-sm text-[var(--rhc-muted)]">{label}</p><p className="mt-1 font-semibold text-[var(--rhc-heading)]">{value}</p></div>)}</div></Card></section>
    <section id="properties" className="mt-5 grid gap-5 xl:grid-cols-[1fr_1fr]"><LinkedProperties compact /><Card title="Digital Property Portfolio"><p className="rhc-body-copy">Only authorized customer-property relationships appear here. Legal ownership records remain in RHC business systems.</p><div className="mt-5"><Web3Button href="/properties" variant="secondary">View all properties</Web3Button></div></Card></section>
    <section id="marketplace" className="mt-5"><Card title="RHC Marketplace"><div className="mb-5 flex flex-wrap gap-2">{['Properties', 'Amica', 'RHC Businesses', 'Partners', 'Services', 'Digital Assets'].map((cat) => <Badge key={cat}>{cat}</Badge>)}</div><DirectoryCards path="/business-services" /></Card></section>
    <section id="transactions" className="mt-5"><TransactionTable /></section>
    <section id="blockchain" className="mt-5 grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><BlockchainStatus /><Card title="Blockchain Activity"><div className="grid gap-3 sm:grid-cols-2">{['Latest Transactions', 'Latest Blocks', 'Smart Contract Activity', 'Token Transfers', 'Digital Property Records', 'Identity Verification Records'].map((item) => <div key={item} className="rounded-lg border border-[var(--rhc-border)] bg-[var(--rhc-surface-secondary)] p-4"><p className="font-semibold text-[var(--rhc-heading)]">{item}</p><p className="mt-1 font-mono text-sm text-[var(--rhc-muted)]">Coming soon — Month 2</p></div>)}</div></Card></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[.95fr_1.05fr]"><Card id="notifications" title="Notification Center"><Notifications /></Card><div id="settings"><SecurityStatus /></div></section>
  </AppShell>;
}
